apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-dcoz-controller
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: role-dcoz-controller
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: role-dcoz-controller-binding
subjects:
- kind: ServiceAccount
  namespace: default
  name: account-dcoz-controller
roleRef:
  kind: ClusterRole
  name: role-dcoz-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcoz-controller
  labels:
    name: dcoz-controller
spec:
  selector:
    matchLabels:
      name: dcoz-controller
  template:
    metadata:
      labels:
        name: dcoz-controller
    spec:
      serviceAccountName: account-dcoz-controller
      containers:
      - name: dcoz-controller
        image: docker.io/springern/dcoz-controller:latest
        command: ["dcoz-controller"]
        args: 
        - -p
        - 4s
        - -d
        - 2s
        - -entrypoint
        - "10.4.5.5:8080"
        - hello-server
        - dcoz-test
        