apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
  labels:
    name: dummy
spec:
  selector:
    matchLabels:
      name: dummy
  template:
    metadata:
      labels:
        name: dummy
    spec:
      containers:
        - name: dcoz-eval-dummy
          image: docker.io/springern/dcoz-eval-dummy:latest
          command: ["python"]
          args: 
            - index.py
            - "8080"
            - req:dummy-1-service.default.svc.cluster.local
            - req:dummy-2-service.default.svc.cluster.local
            - wait:0
            - wait:1
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
spec:
  selector:
    name: dummy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-1
  labels:
    name: dummy-1
spec:
  selector:
    matchLabels:
      name: dummy-1
  template:
    metadata:
      labels:
        name: dummy-1
    spec:
      containers:
        - name: dcoz-eval-dummy
          image: docker.io/springern/dcoz-eval-dummy:latest
          command: ["python"]
          args: 
            - index.py
            - "8080"
            - power:30
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-1-service
spec:
  selector:
    name: dummy-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-2
  labels:
    name: dummy-2
spec:
  selector:
    matchLabels:
      name: dummy-2
  template:
    metadata:
      labels:
        name: dummy-2
    spec:
      containers:
        - name: dcoz-eval-dummy
          image: docker.io/springern/dcoz-eval-dummy:latest
          command: ["python"]
          args: 
            - index.py
            - "8080"
            - power:20
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-2-service
spec:
  selector:
    name: dummy-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080